TAILLE_X = 10
TAILLE_Y = 22
TAILLE_Y_LIMITE = TAILLE_Y - 4
PORT = 9001
ADRESSE = "ws://localhost:"
NOMBRE_DE_JOUEUR = 2
NOMBRE_DE_CHOIX = 3
SCORE_DEPASSEMENT = -1000
NOMBRE_DE_TOUR = 6000
LEVELS = ["random", "smart1","4-heuristic", "6-heuristic", "rein_learn"]
