#!/usr/bin/python3

import Server
import IAClient
import GlobalParameters as gp
import asyncio
import os
import webbrowser

async def javascript_run():
    os.system("gnome-open tetris_ui.html")
    #webbrowser.open("tetris_ui.html")
    #pass


SERVER = Server.Server()

loop = asyncio.get_event_loop()
loop.run_until_complete(SERVER.accept_connections(gp.PORT))
asyncio.ensure_future(javascript_run())
asyncio.ensure_future(SERVER.run_server())
asyncio.ensure_future(IAClient.run())
loop.run_forever()

